services:
  floci:
    build:
      context: .
      dockerfile: Dockerfile.native
    ports:
      - "4566:4566"
      - "6379-6399:6379-6399"
      - "7001-7099:7001-7099"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts:/etc/floci/init/start.d
      - ./scripts:/etc/floci/init/stop.d
    environment:
      FLOCI_SERVICES_DOCKER_NETWORK: floci_default
      FLOCI_SERVICES_RDS_PROXY_BASE_PORT: "7001"
      FLOCI_STORAGE_PERSISTENT_PATH: /app/data
    networks:
      default:
        aliases:
          - localhost.floci.cloud


