FROM eclipse-temurin:25-jre-alpine

WORKDIR /app

RUN mkdir -p /app/data \
    && chown 1001:root /app \
    && chmod "g+rwX" /app \
    && chown 1001:root /app/data

VOLUME /app/data

COPY --chown=1001:root target/quarkus-app quarkus-app/

EXPOSE 4566 6379-6399

ARG VERSION=latest
ENV FLOCI_VERSION=${VERSION}

USER 1001

ENTRYPOINT ["java", "-jar", "quarkus-app/quarkus-run.jar", "-Dquarkus.http.host=0.0.0.0"]